### ISSUE TITLE
Action II.2 in Multithread

### ISSUE THREAD

**Issue by thanhluan001** [armandooj/NachOS#19]
What is supposed to happen in Action II.2, i.e. when an UserThread call Halt() before other threads call UserThreadExit()? 

For the 2nd part, are they asking us to do the protect UserThreadExit() and Halt() so that only one thread can execute that part atomically?

**Comment by armandooj** [comment]
As far as I understood, what should happen is that if even if Halt is called before UserThreadExit(), the program shouldn't finish until al threads exit. Currently the program is killed no mater how many threads were alive.

**Comment by thanhluan001** [comment]
And what happens when there are 2 thread calling Halt() at the same time?

**Comment by armandooj** [comment]
@thanhluan001 Is this issue still valid?

**Comment by thanhluan001** [comment]
No, halt will always stop the program. It's what we want
