### ISSUE TITLE
Thread join

### ISSUE THREAD

**Issue by armandooj** [armandooj/NachOS#26]
We need to implement join. What it should do is to wait for the thread id passed as an argument to finish in order to continue. 

The teacher said: give it a parameter (the parameter where you want to write, more like pthread join)

**Comment by thanhluan001** [comment]
@armandooj Could you give an example for the join? The teacher in class mentions something about returning value. I think it means that one thread can wait for another thread to finish which pass back a value to use for further computation.

**Comment by armandooj** [comment]
@thanhluan001 I think we can use the register 2 as always. And that value would be written only after the thread has finished.

**Comment by thanhluan001** [comment]
@armandooj I mean a c program that use join. Like so:

#include "syscall.h"
void thread2(void *c)
{
  PutChar(* ((char *) c));  
  UserThreadJoin( ??? ); // What to put in the argument of join? We don't know the ID of thread here. 

  UserThreadExit(); 
}

void thread1(void *c)
{
  UserThreadCreate(thread2, c);
  PutChar('2');
  PutString("Long Process");
  
  UserThreadExit(); 
}

int main() {
  
  char ch = 'K';
  char* c = &ch;

  UserThreadCreate(thread1, (void *) c);
  UserJoin
  PutChar('1');
    
  return 0;
}

**Comment by armandooj** [comment]
I think it should be something like:
int tid[N];
int i;

for (i = 0; i < N; i++) {
    tid[i] = UserThreadCreate(print, (void *) c);
}

for (i = 0; i < N; i++) {
    UserThreadJoin(tid[i]);
}

// And possibly make each tread perform a part of a bigger operation so that at the end we can test that the result is the expected value.

**Comment by thanhluan001** [comment]
Do we allow the usethread to wait for multiple threads to complete? In the pdf (Action II.4), it seems it only asks a thread to wait for another thread, not an array of threads like your example. @armandooj

**Comment by armandooj** [comment]
I'm not 100% sure but it's supposed to behave similar as the pthread join.

**Comment by thanhluan001** [comment]
Hey, the thread join is a bit involved. I think i can finish it today. How is the virtual memory going? @armandooj

**Comment by armandooj** [comment]
@thanhluan001 ok, let me know. I'm about to start it, I was doing the "automatically exit a thread"

**Comment by thanhluan001** [comment]
Hey, I think I'm almost finished with the join. In my tests, there are some mistakes but I'll debug it early tomorrow. 

I saw that we have a lot of code in our branches so don't merge or anything before we meet tomorrowt merge or anything before we meet tomorrow</div>
-----Original Message-----

**Comment by thanhluan001** [comment]
Fixed in #33
