### ISSUE TITLE
Fix the report

### ISSUE THREAD

**Issue by armandooj** [armandooj/NachOS#28]
Notes:
Halt and exit are not IO
4.1 : Thread process model description : new thread allocates stack xx
the same behaviour is enforced when user thread trying to execute halt xxxx
internal design and implementation are the same thing

Userthreadcreate : not a class but a function , she doesn't want what we understood but what we implemented 
What we shoud we put : main , when main terminates , the stacks are managed this way , synchronization when the main waites is managed like this ,

Presentation: https://www.overleaf.com/2143299kmprgw#/5461934/
Report:   https://www.overleaf.com/2103293twpvkm#/5348816

**Comment by shubhujf** [comment]
Presentation:
https://www.overleaf.com/2143299kmprgw#/5461934/

**Comment by thanhluan001** [comment]
@Cesar90ss Mina, how's the report going?

**Comment by shubhujf** [comment]
Report link: https://www.overleaf.com/2103293twpvkm#/5348816

Some threading and virtual memory management and some parts of filesys are
missing for now. I have added my part. And rest of the things are fixed as
i think. Also for user tests, I wish to ask you again that Do we have to
include the source code of the user tests(as we have already in our report)
or we just explained about them and then write that how do they work !!!

Thanks.

**Comment by Cesar90ss** [comment]
I am working on the report now and I just pushed the function to change
directory , I strongly believe that in the report we need to write some
parts about the code skeleton

On Sun, Jan 25, 2015 at 1:42 AM, shubhujf <notifications@github.com> wrote:

> Report link: https://www.overleaf.com/2103293twpvkm#/5348816
>
> Some threading and virtual memory management and some parts of filesys are
> missing for now. I have added my part. And rest of the things are fixed as
> i think. Also for user tests, I wish to ask you again that Do we have to
> include the source code of the user tests(as we have already in our
> report)
> or we just explained about them and then write that how do they work !!!
>
> Thanks.
>
> On 25 January 2015 at 00:13, Luan Pham <notifications@github.com> wrote:
>
> > @Cesar90ss <https://github.com/Cesar90ss> Mina, how's the report going?
> >
> > —
> > Reply to this email directly or view it on GitHub
> > <https://github.com/armandooj/NachOS/issues/28#issuecomment-71342353>.
> >
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/armandooj/NachOS/issues/28#issuecomment-71344937>.
>



-- 

Mina Khalil ,
Computer Science Master student University Joseph Fourier - France.
Email: minakhalil1991@gmail.com
Phone: 0660544673

**Comment by Cesar90ss** [comment]
I added the Skeleton of the FileSystem which is basically what do we
understand from filesys , if you guys agree i could add the skeleton also
for the previous parts i will just read it and add it .

As for the code there is only one function missing  so far which is delete
directory , i am half way though but i need to test it and i will push it
today

On Sun, Jan 25, 2015 at 4:40 AM, Mina Khalil <minakhalil1991@gmail.com>
wrote:

> I am working on the report now and I just pushed the function to change
> directory , I strongly believe that in the report we need to write some
> parts about the code skeleton
>
> On Sun, Jan 25, 2015 at 1:42 AM, shubhujf <notifications@github.com>
> wrote:
>
>> Report link: https://www.overleaf.com/2103293twpvkm#/5348816
>>
>> Some threading and virtual memory management and some parts of filesys
>> are
>> missing for now. I have added my part. And rest of the things are fixed
>> as
>> i think. Also for user tests, I wish to ask you again that Do we have to
>> include the source code of the user tests(as we have already in our
>> report)
>> or we just explained about them and then write that how do they work !!!
>>
>> Thanks.
>>
>> On 25 January 2015 at 00:13, Luan Pham <notifications@github.com> wrote:
>>
>> > @Cesar90ss <https://github.com/Cesar90ss> Mina, how's the report
>> going?
>> >
>> > —
>> > Reply to this email directly or view it on GitHub
>> > <https://github.com/armandooj/NachOS/issues/28#issuecomment-71342353>.
>> >
>>
>> —
>> Reply to this email directly or view it on GitHub
>> <https://github.com/armandooj/NachOS/issues/28#issuecomment-71344937>.
>>
>
>
>
> --
>
> Mina Khalil ,
> Computer Science Master student University Joseph Fourier - France.
> Email: minakhalil1991@gmail.com
> Phone: 0660544673
>



-- 

Mina Khalil ,
Computer Science Master student University Joseph Fourier - France.
Email: minakhalil1991@gmail.com
Phone: 0660544673

**Comment by armandooj** [comment]
@shubhujf I remember they said they DO NOT want code in the report, only method definitions (maybe). What we should do is to explain what our tests check for - what possible errors and how we implemented them. What do you think?

**Comment by armandooj** [comment]
@everybody for the report, the teacher said she doesn't want to see what we understood of what it's already there - she knows that. What she expects is what we implemented, how and why. How is everything managed, what happens when X, etc.

**Comment by Cesar90ss** [comment]
ok

On Sun, Jan 25, 2015 at 12:23 PM, Armando Ochoa <notifications@github.com>
wrote:

> @everybody <https://github.com/everybody> for the report, the teacher
> said she doesn't want to see what we understood of what it's already there
> - she knows that. What she expects is what we implemented, how and why. How
> is everything managed, what happens when X, etc.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/armandooj/NachOS/issues/28#issuecomment-71367458>.
>



-- 

Mina Khalil ,
Computer Science Master student University Joseph Fourier - France.
Email: minakhalil1991@gmail.com
Phone: 0660544673

**Comment by shubhujf** [comment]
@everybody for the report, I agree with Armando, I also think that we
should not include the code for test cases in our report. We can explain
about the test cases and how do they work. Also @Mina, the Skeleton of the
FileSystem which you added is just for understanding, which is already
there in the code. So I think.. she doesn't want what we understood but
what we implemented. What do you think. Also I am thinking to remove the
source code from the report. Ok for all ?

**Comment by Cesar90ss** [comment]
ok no problem with me

On Sun, Jan 25, 2015 at 6:29 PM, shubhujf <notifications@github.com> wrote:

> @everybody for the report, I agree with Armando, I also think that we
> should not include the code for test cases in our report. We can explain
> about the test cases and how do they work. Also @Mina, the Skeleton of the
> FileSystem which you added is just for understanding, which is already
> there in the code. So I think.. she doesn't want what we understood but
> what we implemented. What do you think. Also I am thinking to remove the
> source code from the report. Ok for all ?
>
> On 25 January 2015 at 12:23, Armando Ochoa <notifications@github.com>
> wrote:
>
> > @everybody <https://github.com/everybody> for the report, the teacher
> > said she doesn't want to see what we understood of what it's already
> there
> > - she knows that. What she expects is what we implemented, how and why.
> How
> > is everything managed, what happens when X, etc.
> >
> > —
> > Reply to this email directly or view it on GitHub
> > <https://github.com/armandooj/NachOS/issues/28#issuecomment-71367458>.
> >
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/armandooj/NachOS/issues/28#issuecomment-71382304>.
>



-- 

Mina Khalil ,
Computer Science Master student University Joseph Fourier - France.
Email: minakhalil1991@gmail.com
Phone: 0660544673

**Comment by Cesar90ss** [comment]
I added the final part about changing path to the report
