### ISSUE TITLE
Use a unique identifier for threads

### ISSUE THREAD

**Issue by armandooj** [armandooj/NachOS#36]

**Comment by armandooj** [comment]
Also, add a real test. I.e consumer-producer, dinning philosophers

**Comment by thanhluan001** [comment]
This should be a unique identifier for threads and processes alike. We can reuse the old ID as the stack identifier but the new ID should be in machine and always increasing. Like so:

private int processID = 100;

int getNewID() {
   lock;
   processID ++;
   unlock;
   return processID; 
}
