### ISSUE TITLE
Wait for other processes to finish

### ISSUE THREAD

**Issue by thanhluan001** [armandooj/NachOS#39]
It's a join for processes. If a process execute exit then it needs to wait for other processes to finish. It's also true for threads (which already implemented). See if these features (for both process and thread) can be combined.

**Comment by thanhluan001** [comment]
@armandooj Did you do anything about the join? I see some code in machine.cc and it seems to work for some cases. I'm just confused. Could you next time don't leave anything half-baked?

**Comment by thanhluan001** [comment]
Is UserThreadJoin working? Why my code's commented out? Now I am really confused. @armandooj

**Comment by armandooj** [comment]
@thanhluan001 I was testing it, but if you look carefully it's the same, I'm just printing stuff and have an if to check if there's still something.. you can use the commented code. And no, I didn't implement it, I just wrote the dummy function..

**Comment by thanhluan001** [comment]
check your facebook message
