### ISSUE TITLE
Merge all code in file system

### ISSUE THREAD

**Issue by thanhluan001** [armandooj/NachOS#41]
As discussed, we need a stable branch for file system.

**Comment by thanhluan001** [comment]
The code for virtual address now on master. Pull it and merge to your branch. It has the ForkExec to test your concurrency access.

**Comment by thanhluan001** [comment]
@shubhujf  The merge is going well? Can you collaborate with @peterhan1987  to get all the code in 1 branch? Again, nothing fancy like concurrency access is expected, but I'd like to have all the code in 1 branch so that you can use the latest feature like the ForkExec of multithreading.

**Comment by shubhujf** [comment]
Previous part of jing han was merged into file_sys with my part but for the
rest of parts, we will merge them tomorrow.

**Comment by peterhan1987** [comment]
Hi shubham,mina

I have merged everything in master into my own branch 'Jin', but i still miss the part of directory, and everything works perfect on this branch. You two can check in your code in this branch.

Hi shubham,

I do not know why but seems like part of file size feature can not work fine in 'file_sys'. try to test the command 'nachos_filesys -t' you can see the error, that is why i think you two can check in your code in my branch so that we can get rid of that error.

**Comment by Cesar90ss** [comment]
there is no command -t , it is either -f to format or -l to list and it is
working fine with me

On Sun, Jan 25, 2015 at 7:00 PM, peterhan1987 <notifications@github.com>
wrote:

> Hi shubham,mina
>
> I have merged everything in master into my own branch 'Jin', but i still
> miss the part of directory, and everything works perfect on this branch.
> You two can check in your code in this branch.
>
> Hi shubham,
>
> I do not know why but seems like part of file size feature can not work
> fine in 'file_sys'. try to test the command 'nachos_filesys -t' you can see
> the error, that is why i think you two can check in your code in my branch
> so that we can get rid of that error.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/armandooj/NachOS/issues/41#issuecomment-71383491>.
>



-- 

Mina Khalil ,
Computer Science Master student University Joseph Fourier - France.
Email: minakhalil1991@gmail.com
Phone: 0660544673

**Comment by Cesar90ss** [comment]
Hey guys , the last part of deleting a directory is almost done but there
is one function missing in shubham code that needs to be added in order for
it to work (Get the current directory ) . I told him and we will finish it
by tomorrow and merge the changes

On Sun, Jan 25, 2015 at 10:50 PM, Mina Khalil <minakhalil1991@gmail.com>
wrote:

> there is no command -t , it is either -f to format or -l to list and it is
> working fine with me
>
> On Sun, Jan 25, 2015 at 7:00 PM, peterhan1987 <notifications@github.com>
> wrote:
>
>> Hi shubham,mina
>>
>> I have merged everything in master into my own branch 'Jin', but i still
>> miss the part of directory, and everything works perfect on this branch.
>> You two can check in your code in this branch.
>>
>> Hi shubham,
>>
>> I do not know why but seems like part of file size feature can not work
>> fine in 'file_sys'. try to test the command 'nachos_filesys -t' you can see
>> the error, that is why i think you two can check in your code in my branch
>> so that we can get rid of that error.
>>
>> —
>> Reply to this email directly or view it on GitHub
>> <https://github.com/armandooj/NachOS/issues/41#issuecomment-71383491>.
>>
>
>
>
> --
>
> Mina Khalil ,
> Computer Science Master student University Joseph Fourier - France.
> Email: minakhalil1991@gmail.com
> Phone: 0660544673
>



-- 

Mina Khalil ,
Computer Science Master student University Joseph Fourier - France.
Email: minakhalil1991@gmail.com
Phone: 0660544673

**Comment by Cesar90ss** [comment]
the last part now is working , we could merge tomorrow

On Mon, Jan 26, 2015 at 2:13 AM, Mina Khalil <minakhalil1991@gmail.com>
wrote:

> Hey guys , the last part of deleting a directory is almost done but there
> is one function missing in shubham code that needs to be added in order for
> it to work (Get the current directory ) . I told him and we will finish it
> by tomorrow and merge the changes
>
> On Sun, Jan 25, 2015 at 10:50 PM, Mina Khalil <minakhalil1991@gmail.com>
> wrote:
>
>> there is no command -t , it is either -f to format or -l to list and it
>> is working fine with me
>>
>> On Sun, Jan 25, 2015 at 7:00 PM, peterhan1987 <notifications@github.com>
>> wrote:
>>
>>> Hi shubham,mina
>>>
>>> I have merged everything in master into my own branch 'Jin', but i still
>>> miss the part of directory, and everything works perfect on this branch.
>>> You two can check in your code in this branch.
>>>
>>> Hi shubham,
>>>
>>> I do not know why but seems like part of file size feature can not work
>>> fine in 'file_sys'. try to test the command 'nachos_filesys -t' you can see
>>> the error, that is why i think you two can check in your code in my branch
>>> so that we can get rid of that error.
>>>
>>> —
>>> Reply to this email directly or view it on GitHub
>>> <https://github.com/armandooj/NachOS/issues/41#issuecomment-71383491>.
>>>
>>
>>
>>
>> --
>>
>> Mina Khalil ,
>> Computer Science Master student University Joseph Fourier - France.
>> Email: minakhalil1991@gmail.com
>> Phone: 0660544673
>>
>
>
>
> --
>
> Mina Khalil ,
> Computer Science Master student University Joseph Fourier - France.
> Email: minakhalil1991@gmail.com
> Phone: 0660544673
>



-- 

Mina Khalil ,
Computer Science Master student University Joseph Fourier - France.
Email: minakhalil1991@gmail.com
Phone: 0660544673
