### ISSUE TITLE
Cannot run any program while adding network to the current flavor

### ISSUE THREAD

**Issue by armandooj** [armandooj/NachOS#42]
Hey guys, the problem is with ALL programs. If for example we use the step4 exactly as we had it before and only add network, all programs (-x) fail after that:

Assertion failed: line 319, file "../machine/sysdep.cc"

Any clues?. 
Again, Making works but we cannot run anything. I'm going to go back working to virtual memory, if someone could check this that would be nice.

Branch: feat_network

**Comment by thanhluan001** [comment]
I gonna do the virtual memory also. Check this back tomorrow.
