### ISSUE TITLE
Errors are not being catched properly

### ISSUE THREAD

**Issue by armandooj** [armandooj/NachOS#43]
If we have time, add proper error-handling for both threads and processes creation. Currently the creation may fail (i.e no enough memory or stack space), we do nothing and continue the execution -which could lead to more errors.

**Comment by thanhluan001** [comment]
@armandooj  Did you fix it?

**Comment by armandooj** [comment]
@thanhluan001 It was fixed before, at least for the stack. Are we going to handle more errors?
