### ISSUE TITLE
List of possible bugs.

### ISSUE THREAD

**Issue by armandooj** [armandooj/NachOS#47]
Stuff that may be improved later.

- If a thread calls Join twice, two conditions are created. What would happen when that thread finishes?
- A thread's PID is limited by the size of an int. What if we have thousands of threads?. Right now that's unlikely but it would be nice to get rid of that limitation.
- PutChar should also set the value in the parameter, if any. Right now it only returns the value.

**Comment by thanhluan001** [comment]
The size of an int is big. I think we're compiled in an 32 bit so the maximum of Int would around 2^30-1073741823 processes. But we worry about that after all is done

**Comment by thanhluan001** [comment]
When a thread call a join, either the join return right away or the thread goes to sleep. So, in theory, a thread can't call join twice. It needs to return from a join before doing another join, and the system would only see 1 join from that thread.
