### ISSUE TITLE
Wish list: Shell

### ISSUE THREAD

**Issue by thanhluan001** [armandooj/NachOS#48]
I'd like the bonus question of doing a shell in Virtual Memory. Doing this would make it very easy to do the demo in the final report.

**Comment by armandooj** [comment]
@thanhluan001 Up to you. I just started playing around with network but if you're working on that I can give the shell a try now.

**Comment by thanhluan001** [comment]
It's a wishlist. This is not to be touched unless all required features are implemented. My estimate is that we can do this starting Tuesday or Weds.

**Comment by thanhluan001** [comment]
Ongoing
