### ISSUE TITLE
Test conditions / complete consumer-producer test

### ISSUE THREAD

**Issue by armandooj** [armandooj/NachOS#51]
I wrote the skeleton of the program, the purpose is to test the Conditions Luan implemented. I suspect the may fail because Conditions should wait and signal the Lock passed as an argument and right now we're ignoring them (synch.h, synch.cc).

The skeleton I wrote is under userprog, go to the branch feat_consumer and see the files I changed. To run the program write: ./nachos-step6 -co

I left lot's of comments :)

**Comment by Cesar90ss** [comment]
@armandooj  : I fixed the code and now it is compiling correctly , the logic seems fine but I don't know how to test it with multiple threads . we can do it tomorrow

**Comment by Cesar90ss** [comment]
It just needed to be tested using threads
