### ISSUE TITLE
New merge code in master

### ISSUE THREAD

**Issue by thanhluan001** [armandooj/NachOS#54]
New merged code is in master. Everyone should be using nachos-final now. Delete everything on your build and make again and use only nachos-final. Branch again from this point if you wanw to. @armandooj @shubhujf @peterhan1987 @Cesar90ss

**Comment by Cesar90ss** [comment]
ok

On Wed, Jan 28, 2015 at 7:33 PM, Luan Pham <notifications@github.com> wrote:

> New merged code is in master. Everyone should be using nachos-final now.
> Delete everything on your build and make again and use only nachos-final.
> @armandooj <https://github.com/armandooj> @shubhujf
> <https://github.com/shubhujf> @peterhan1987
> <https://github.com/peterhan1987> @Cesar90ss
> <https://github.com/Cesar90ss>
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/armandooj/NachOS/issues/54>.
>



-- 

Mina Khalil ,
Computer Science Master student University Joseph Fourier - France.
Email: minakhalil1991@gmail.com
Phone: 0660544673

**Comment by Cesar90ss** [comment]
Guys , I just pulled from master and when I try to make i get this error ! :


On Wed, Jan 28, 2015 at 10:41 PM, Mina Khalil <minakhalil1991@gmail.com>
wrote:

> ok
>
> On Wed, Jan 28, 2015 at 7:33 PM, Luan Pham <notifications@github.com>
> wrote:
>
>> New merged code is in master. Everyone should be using nachos-final now.
>> Delete everything on your build and make again and use only nachos-final.
>> @armandooj <https://github.com/armandooj> @shubhujf
>> <https://github.com/shubhujf> @peterhan1987
>> <https://github.com/peterhan1987> @Cesar90ss
>> <https://github.com/Cesar90ss>
>>
>> —
>> Reply to this email directly or view it on GitHub
>> <https://github.com/armandooj/NachOS/issues/54>.
>>
>
>
>
> --
>
> Mina Khalil ,
> Computer Science Master student University Joseph Fourier - France.
> Email: minakhalil1991@gmail.com
> Phone: 0660544673
>



-- 

Mina Khalil ,
Computer Science Master student University Joseph Fourier - France.
Email: minakhalil1991@gmail.com
Phone: 0660544673

**Comment by Cesar90ss** [comment]
../threads/main.cc: In function ‘int main(int, char**)’:
../threads/main.cc:269:37: error: ‘MailWait’ was not declared in this scope
         MailWait (atoi (*(argv + 1)));


On Wed, Jan 28, 2015 at 10:44 PM, Mina Khalil <minakhalil1991@gmail.com>
wrote:

> Guys , I just pulled from master and when I try to make i get this error !
> :
>
>
> On Wed, Jan 28, 2015 at 10:41 PM, Mina Khalil <minakhalil1991@gmail.com>
> wrote:
>
>> ok
>>
>> On Wed, Jan 28, 2015 at 7:33 PM, Luan Pham <notifications@github.com>
>> wrote:
>>
>>> New merged code is in master. Everyone should be using nachos-final now.
>>> Delete everything on your build and make again and use only nachos-final.
>>> @armandooj <https://github.com/armandooj> @shubhujf
>>> <https://github.com/shubhujf> @peterhan1987
>>> <https://github.com/peterhan1987> @Cesar90ss
>>> <https://github.com/Cesar90ss>
>>>
>>> —
>>> Reply to this email directly or view it on GitHub
>>> <https://github.com/armandooj/NachOS/issues/54>.
>>>
>>
>>
>>
>> --
>>
>> Mina Khalil ,
>> Computer Science Master student University Joseph Fourier - France.
>> Email: minakhalil1991@gmail.com
>> Phone: 0660544673
>>
>
>
>
> --
>
> Mina Khalil ,
> Computer Science Master student University Joseph Fourier - France.
> Email: minakhalil1991@gmail.com
> Phone: 0660544673
>



-- 

Mina Khalil ,
Computer Science Master student University Joseph Fourier - France.
Email: minakhalil1991@gmail.com
Phone: 0660544673
