### ISSUE TITLE
Script to copy file to Nachos file system

### ISSUE THREAD

**Issue by thanhluan001** [armandooj/NachOS#55]
@Cesar90ss We need a script file to do the import all files automatically to the Nachos file system. Or every time we compile the code again then we have to manually copy the file to Nachos. Can you do an .sh file? After that, remember  to change the permission so that you can execute the script. Any problem, let me know.

**Comment by Cesar90ss** [comment]
Hey , the code wasn't compiling so I couldn't test it but this is the script :


./nachos-final -f 
./nachos-final -cp ListDirectory ListDirectory
./nachos-final -cp MakeDir MakrDir
./nachos-final -cp ChangeDir ChangeDir
./nachos-final -cp PutcharCommand PutcharCommand
./nachos-final -cp PutStringCOmmand PutStringCOmmand
./nachos-final -cp GetCharCommand GetCharCommand
./nachos-final -cp GetStringCommand GetStringCommand
./nachos-final -cp PutIntCommand PutIntCommand
./nachos-final -cp GetIntCommand GetIntCommand
./nachos-final -cp DeleteDirectory DeleteDirectory 
@thanhluan001
