### ISSUE TITLE
Sample to copy file

### ISSUE THREAD

**Issue by thanhluan001** [armandooj/NachOS#56]
@Cesar90ss Could you give me a sample command line to copy file to Nachos? I need that to test my code on the new shell. I think a command to copy shell and putchar is enough.

**Comment by Cesar90ss** [comment]
./nachos-final -cp  ../filesys/test/small nameofthefile

**Comment by Cesar90ss** [comment]
@thanhluan001

**Comment by Cesar90ss** [comment]
done

On Wed, Jan 28, 2015 at 9:20 PM, Luan Pham <notifications@github.com> wrote:

> Assigned #56 <https://github.com/armandooj/NachOS/issues/56> to @Cesar90ss
> <https://github.com/Cesar90ss>.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/armandooj/NachOS/issues/56#event-226354109>.
>



-- 

Mina Khalil ,
Computer Science Master student University Joseph Fourier - France.
Email: minakhalil1991@gmail.com
Phone: 0660544673
